spring:
  application:
    name: parking-system-backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ParkingManagementSystem;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true

    properties:
      hibernate:
        format_sql: true